server:
  port: 8123
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ten_api
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD:}
  redis:
    database: 0
    host: localhost
    port: 6379
    password: ${SPRING_REDIS_PASSWORD:}
